#!/usr/bin/env bash

# Video drivers by vendor
PKG_GRAPHICS_NVIDIA="nvidia nvidia-utils lib32-nvidia-utils"
PKG_GRAPHICS_AMD="xf86-video-amdgpu mesa lib32-mesa vulkan-radeon"
PKG_GRAPHICS_INTEL="xf86-video-intel mesa lib32-mesa"
