#!/usr/bin/env bash

# Installed on all systems
PKG_SYSTEM="systemd-boot-pacman-hook pacman-contrib smbclient cronie nohang usbutils"
PKG_UTILS="zip unzip openssh autossh git tig bat htop imagemagick jq rsync gnupg"
PKG_DOCKER="docker docker-compose docker-buildx"

PACKAGES="$PKG_SYSTEM $PKG_UTILS $PKG_DOCKER"

echo "Installing packages"
yay --noconfirm --needed -S $PACKAGES || exit $?

echo "Configuring cronie"
sudo systemctl enable --now cronie.service

echo "Configuring sshd"
sudo systemctl enable sshd.service

echo "Configuring nohang"
sudo systemctl enable --now nohang.service

echo "Configuring docker"
sudo systemctl enable --now docker.service
sudo usermod -a -G docker $USER
docker buildx install

echo "Updating the vcsh repo origin URL"
vcsh base remote set-url origin "git@github.com:stilesdev/dotfiles.git"

