#!/usr/bin/env bash

PACKAGES="\
fnm-bin \
fzf \
go \
jq \
neofetch \
neovim \
ripgrep \
starship \
tig \
tmux \
vim \
wezterm \
zsh \
zsh-autosuggestions \
zsh-history-substring-search \
zsh-syntax-highlighting \
"

echo "Installing packages"
sudo pacman -S --noconfirm --needed $PACKAGES || exit $?

if ! command -v node > /dev/null 2>&1; then
    echo "Installing nodejs using fnm"
    fnm install v20
    fnm default v20
fi

echo "Installing sessionizer"
go install github.com/stilesdev/sessionizer@latest

echo "Setting shell to zsh"
sudo chsh -s /usr/bin/zsh $USER

echo "Updating the vcsh repo origin URL"
vcsh cli remote set-url origin "git@github.com:stilesdev/dotfiles-cli.git"
