#!/usr/bin/env bash

PACKAGES="\
fnm-bin \
fzf \
go \
neofetch \
neovim \
ripgrep \
starship \
tmux \
vim \
wezterm \
zsh \
zsh-autosuggestions \
zsh-history-substring-search \
zsh-syntax-highlighting \
"

echo "Installing packages"
yay -S --noconfirm --needed $PACKAGES || exit $?

#echo "Updating the vcsh repo origin URL"
#vcsh cli remote set-url origin "git@github.com:stilesdev/dotfiles-cli.git"
