#!/usr/bin/env bash

PACKAGES="\
neofetch \
neovim \
ripgrep \
starship \
vim \
wezterm \
zsh \
"

echo "Installing packages"
sudo pacman -S --noconfirm --needed $PACKAGES || exit $?

#echo "Updating the vcsh repo origin URL"
#vcsh cli remote set-url origin "git@github.com:stilesdev/dotfiles-cli.git"
