# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$lua\
$nodejs\
$ocaml\
$php\
$python\
$rust\
$azure\
$cmd_duration\
$jobs\
$character"""

right_format = "$status"

add_newline = false

palette = "catppuccin_mocha"

[username]
format = '[$user]($style)'

[hostname]
ssh_symbol = '@'
style = 'bold maroon'
format = '[$ssh_symbol$hostname]($style) '

[directory]
truncation_length = 0
style = 'bold mauve'
read_only = ' '

[git_branch]
symbol = ' '
style = 'bold sapphire'

[git_commit]
tag_disabled = false
tag_symbol = ' 󰓹 '

[package]
symbol = ' '
style = 'bold peach'
format = '[$symbol$version]($style) '

[lua]
symbol = ' '

[ocaml]
symbol = ' '

[php]
symbol = '󰌟 '
style = 'bold mauve'

[python]
symbol = ' '

[rust]
symbol = ' '

[azure]
symbol = ' '

[status]
disabled = false
symbol = ' '

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

