#!/usr/bin/env bash

PKG_YUBIKEY="gnupg2 pinentry pcsclite ccid libusb-compat gcr"
PKG_DESKTOP="xorg-server xorg-xrdb i3-gaps polybar compton feh rofi lightdm lightdm-slick-greeter betterlockscreen"
PKG_FONTS="otf-overpass adobe-source-code-pro-fonts otf-hasklig otf-fira-code otf-font-awesome"
PKG_APPS="jetbrains-toolbox code synergy qt5-base openssh zsh konsole thunar moka-icon-theme faba-icon-theme scrot imagemagick spotify-stable jq systemd-boot-pacman-hook google-chrome"
PKG_NVIDIA="nvidia nvidia-utils lib32-nvidia-utils"
PKG_INTEL="xf86-video-intel mesa lib32-mesa"

case $(hostname) in
bismuth*)
    PACKAGES="$PKG_YUBIKEY $PKG_DESKTOP $PKG_FONTS $PKG_APPS $PKG_NVIDIA"
    ;;
arjia* | gallium*)
    PACKAGES="$PKG_YUBIKEY $PKG_DESKTOP $PKG_FONTS $PKG_APPS $PKG_INTEL"
    ;;
esac

echo "Installing packages"
yay --noconfirm --needed -S $PACKAGES

echo "Installing nvm"
nvm_version=$(curl -sS https://api.github.com/repos/creationix/nvm/releases/latest | jq -r '.tag_name')
curl -sS -o- https://raw.githubusercontent.com/creationix/nvm/$nvm_version/install.sh | bash

echo "Configuring sshd"
sudo sed -i "s/^\#\?\(PermitRootLogin\).*$/\1 no/" /etc/ssh/sshd_config
sudo systemctl enable sshd.service

echo "Configuring lightdm to use slick-greeter"
sudo sed -i "s/^\#\?\(greeter\-session=\).*$/\1lightdm\-slick\-greeter/" /etc/lightdm/lightdm.conf

echo "Enabling lightdm to start at boot"
sudo systemctl enable lightdm.service

echo "Configuring synergy client to start on login screen"
if ! grep "^greeter-setup-script=/usr/bin/synergyc" /etc/lightdm/lightdm.conf; then
    echo -e "\n[SeatDefaults]\ngreeter-setup-script=/usr/bin/synergyc --enable-crypto argon.stiles.me" | sudo tee -a /etc/lightdm/lightdm.conf
fi

echo "Creating wallpapers directory and generating placeholder wallpaper"
mkdir -p ~/Pictures/Wallpapers
convert -size 1920x1080 xc:black ~/Pictures/Wallpapers/placeholder.jpg

echo "Setting up GPG key"
systemctl --user mask --now gpg-agent.service gpg-agent.socket gpg-agent-ssh.socket gpg-agent-extra.socket gpg-agent-browser.socket
sudo systemctl enable pcscd
sudo systemctl start pcscd
if ! gpg --card-status; then
    echo "Failed to detect YubiKey. Plug in the YubiKey and try running the bootstrap script again"
elif ! gpg --keyserver keys.gnupg.net --recv C0AC1B5B; then
    echo "Failed to retrieve key from keyserver. Check internet connectivity and try running the bootstrap script again"
else
    echo -e "5\ny\n" | gpg --command-fd 0 --expert --edit-key C0AC1B5B trust
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:mstiles92/dotfiles.git"